name: tests
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install -r requirements.txt
      - run: pip install pytest pytest-cov ruff black
      - run: ruff check . --output-format=github
      - run: ruff format . --check
      - run: black . -l 100 --check
      - run: pytest --cov=web_flask --cov=core
